package main

import (
	"encoding/json"
	"fmt"
	"strings"
	"text/template"
)

// PackageName turns POL-AI-003 into pol_ai_003.
func PackageName(id string) string {
	return strings.ToLower(strings.ReplaceAll(id, "-", "_"))
}

func js(v any) string { b, _ := json.Marshal(v); return string(b) }

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

var funcs = template.FuncMap{
	"json":    js,
	"oneLine": oneLine,
	"pkg":     PackageName,
	"split":   func(s string) []string { return strings.Split(s, ".") },
}

// One rule per gateway statement. Every value from the policy is emitted
// through `json`, so it can only ever be a Rego string or array literal.
var policyTmpl = template.Must(template.New("policy").Funcs(funcs).Parse(`# GENERATED by policyc from {{.P.PolicyID}} v{{.P.Version}}. Do not edit.
# Source sha256: {{.Hash}}
# Approved by: {{range $i, $a := .A.Approvals}}{{if $i}}, {{end}}{{$a.Role}} ({{$a.User}}){{end}}
package aiplane.{{pkg .P.PolicyID}}

policy_id := {{json .P.PolicyID}}

policy_version := {{json .P.Version}}

# Rollout mode for the calling app: "monitor" logs only, "enforce" acts.
default mode := "enforce"

mode := m if m := data.aiplane.rollout[input.app.id][policy_id]

exception_active(statement) if {
	some e in data.aiplane.exceptions
	e.policy_id == policy_id
	e.statement == statement
	e.app == input.app.id
	time.parse_rfc3339_ns(e.expires) > time.now_ns()
}
{{range .Gateway}}
# Statement {{.ID}}: {{oneLine .Text}}
decisions contains {"statement": {{json .ID}}, "action": {{json .Action}}, "mode": mode, "finding_ids": ids} if {
{{- range .AppliesWhen}}
	input.{{.Field}} == {{json .Equals}}
{{- end}}
{{- range .Unless}}{{if .Contains}}
	not {{json .Contains}} in object.get(input, {{json (split .Field)}}, [])
{{- else}}
	object.get(input, {{json (split .Field)}}, null) != {{json .Equals}}
{{- end}}{{end}}
	not exception_active({{json .ID}})
	ids := [f.id | some f in input.findings; f.type in {{json .Detect}}]
	count(ids) > 0
}
{{end}}`))

// Tests are generated from the same statements: each rule must fire when
// its conditions hold, stay quiet for other data types, and stay quiet when
// an "unless" condition is met. They run before any bundle is built.
var testTmpl = template.Must(template.New("test").Funcs(funcs).Parse(`# GENERATED by policyc. Do not edit.
package aiplane.{{pkg .P.PolicyID}}_test

import data.aiplane.{{pkg .P.PolicyID}} as p
{{range .Tests}}
test_{{.Name}} if {
	matched := {d | some d in p.decisions; d.statement == {{json .Statement}}} with input as {{json .Input}}
	{{if .Expect}}some d in matched
	d.action == {{json .Action}}{{else}}count(matched) == 0{{end}}
}
{{end}}`))

type testCase struct {
	Name, Statement, Action string
	Expect                  bool
	Input                   map[string]any
}

func buildTests(gw []Statement) []testCase {
	var out []testCase
	for _, s := range gw {
		base := func(findingType string) map[string]any {
			in := map[string]any{
				"app":         map[string]any{"id": "policyc-test-app", "approved_for": []string{}},
				"destination": map[string]any{"provider": "test", "hosting": "self-hosted"},
				"findings":    []map[string]any{{"id": "f1", "type": findingType}},
			}
			for _, c := range s.AppliesWhen {
				setField(in, c.Field, c.Equals)
			}
			return in
		}
		name := strings.ReplaceAll(s.ID, ".", "_")
		for _, d := range s.Detect {
			out = append(out, testCase{
				Name:      fmt.Sprintf("s%s_fires_on_%s", name, strings.ReplaceAll(d, ".", "_")),
				Statement: s.ID, Action: s.Action, Expect: true, Input: base(d),
			})
		}
		out = append(out, testCase{
			Name: "s" + name + "_ignores_other_data", Statement: s.ID, Input: base("other.type"),
		})
		for i, c := range s.Unless {
			in := base(s.Detect[0])
			if c.Contains != "" {
				setField(in, c.Field, []string{c.Contains})
			} else {
				setField(in, c.Field, c.Equals)
			}
			out = append(out, testCase{
				Name: fmt.Sprintf("s%s_skipped_when_unless_%d", name, i+1), Statement: s.ID, Input: in,
			})
		}
	}
	return out
}

func setField(in map[string]any, path string, v any) {
	parts := strings.Split(path, ".")
	m := in
	for _, p := range parts[:len(parts)-1] {
		m = m[p].(map[string]any)
	}
	m[parts[len(parts)-1]] = v
}
